### ISSUE TITLE
permission denied when accsessing through Apache after setup

### ISSUE THREAD

**Issue by cwittern** [WebEntity/Installation-guide-for-GitLab-on-OS-X#37]
Hi there,
first of all many thanks for your installation guide.  I have been using gitlab for about 18 months, but installation is still daunting.  Now I need to setup a new server.  I followed your instructions to the dot and can access the gitlab instance on 127.0.0.1:8080, but not through the front-facing Apache instance.  I have no idea how to debug this and what could be wrong, so any help would be greatly appreciated.

Chris

**Comment by CiTroNaK** [comment]
Check Apache vhost config for your new site and then restart Apache with

```
sudo serveradmin stop web
sudo serveradmin start web
```
