### ISSUE TITLE
Installing libiconv

### ISSUE THREAD

**Issue by mrkodssldrf** [WebEntity/Installation-guide-for-GitLab-on-OS-X#41]
Installing libiconv - Not really an issue 

Current user has no permissions on current folder __</Users/git/gitlab>__

replace __wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.13.1.tar.gz__ with __sudo -u git wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.13.1.tar.gz__

**Comment by CiTroNaK** [comment]
Thank you. 

I have on to do the revision of the guide. I not sure that is necessary to install libiconv from the source anymore. If I find the opposite, I will update the guide :-)
