### ISSUE TITLE
MySQL and Postgres instructions are mixed up now

### ISSUE THREAD

**Issue by adsche** [WebEntity/Installation-guide-for-GitLab-on-OS-X#48]
Hi,

the commit 5ad6a8d13d5f02f5a3624d2c34b772dfe921d0c5, contrary to its commit message, mixed the two instructions up. They were right before.

Note that parameter `--without` of `bundle install` takes a list (space-separated) of arguments [1]. So in fact, you are currently trying to install without the module that you actually want to use.

[1] http://bundler.io/v1.9/man/bundle-install.1.html

**Comment by scottcc** [comment]
+1 Yes - they are currently incorrect. We should revert that part.

**Comment by adsche** [comment]
We actually ended up having to do

    sudo bundle install --deployment --without development test postgres aws --with mysql

However, that might have just been because, per the manpage, `--without` values are cached and we did the wrong command before. On the other hand, the explicit `--with mysql` can not hurt here and it might clear up confusion with the line that lead to the commit in question. So I'd suggest adding that as well.

**Comment by scottcc** [comment]
I had to clean up the .bundle/config (as my previous --without caused it to get written, and older values aren't pruned). I did just open a PR to at least fix the original swap, here: https://github.com/WebEntity/Installation-guide-for-GitLab-on-OS-X/pull/53

I'll leave it up to the maintainer if he wants to add the explicit `--with mysql` (I have no problem with that).

**Comment by CiTroNaK** [comment]
Fixed.
