### ISSUE TITLE
bundle/gem commands should probably be run as user git

### ISSUE THREAD

**Issue by adsche** [WebEntity/Installation-guide-for-GitLab-on-OS-X#50]
Hi,

in sect. 8, subsection "Install Gems", I would recommend running the commands `gem install bundler` and `bundle install ...` as user `git`. The reason is, that otherwise it seems these commands are run in root's ruby environment. That is probably different from the one of user git, though. Also, there will be some directories created (`.bundle` or something) that will be owned by root.
This was the cause of the installation failing for us recently. (I would send you a full error report if I had it handy, but i have not anymore, sorry.)

So, my recommendations: Change

    sudo gem install bundler
    sudo bundle install --deployment --without development test <mysql/postgres> aws

to

    sudo -u git -H -i gem install bundler
    sudo -u git -H -i bundle install --deployment --without development test <mysql/postgres> aws

**Comment by CiTroNaK** [comment]
Thanks.
