### ISSUE TITLE
bundle install error -- "Could not locate Gemfile"

### ISSUE THREAD

**Issue by bobtiki** [WebEntity/Installation-guide-for-GitLab-on-OS-X#54]
Hi there. I'm guessing this might be more of a support request, but as one line of the walkthrough isn't working for me, I thought I'd ask. In case it's relevant, I am also running OS X Server and using Postgres.app as the database on this machine.

Since I'm installing for use with with Postgres, I get to this line under the [Install Gems](https://github.com/WebEntity/Installation-guide-for-GitLab-on-OS-X#install-gems) section:

`sudo -u git -H -i bundle install --deployment --without development test mysql aws`

It returns the error `Could not locate Gemfile`

I am in the `/Users/git/gitlab` directory, so I've gotten this far successfully. I am running it from the directory with the Gemfile in it. *“It’s right there!”* I shout at the computer.

If I try to force it to locate the Gemfile with:

`sudo -u git -H -i BUNDLE_GEMFILE="Gemfile" bundle install --deployment --without development test mysql aws`

It then returns the error, `The --deployment flag requires a Gemfile.lock. Please make sure you have checked your Gemfile.lock into version control before deploying.`

In an effort to comply, I ran:

    $ sudo -u git git add Gemfile
    $ sudo -u git git add Gemfile.lock
    $ sudo -u git git commit -m "Updated Gemfile and Gemfile.lock after changes"
    
    [7-12-stable bf9c135] Updated Gemfile and Gemfile.lock after changes
     Committer: Git Lab <git@example.com>
    […]
     2 files changed, 4 insertions(+), 4 deletions(-)

…but alas, after running the `bundle install` command after this, I still get the same error.

Is there a workaround to resolve this? Unfortunately, I do not know enough about the process to offer a PR. Thanks for any help!

**Comment by davecunnington** [comment]
We have tried on 3 different Macs (with different versions) and had this same issue. It will work with just sudo (without using git user) but this leads to other issues down the line. 

I think that using sudo led us to also have issues further on with "Could not locate rake-10.4.2" even though it was clearly downloaded and installed with the gems existing in the folder.

If we pushed the installs through (sudo etc.) we could get GitLab to run but experienced random 500 errors with no logs being written.

**Comment by CiTroNaK** [comment]
It looks like problem with ruby (`rbenv`). Please, send me the output of this commands:
```
ruby -v
sudo su git
ruby -v
```

**Comment by davecunnington** [comment]
Thanks CiTroNaK, both pointed to the exact same version of Ruby (ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]).

I discovered that `sudo su git` and completing the commands, e.g. `bundle install --deployment --without development test postgres aws` and omitting the `sudo -u git -H -i` worked fine.

**Comment by CiTroNaK** [comment]
Hm, ok, that is good news. Could you please try "which bundle" same way. Thanks.

**Comment by davecunnington** [comment]
Ah ok, as sudo or admin user’s it is `/usr/bin/bundle` but as git user it is `/Users/git/.rbenv/shims/bundle`.




----  ---  --  ----  ---  --  ---  --  ----  --  ---  --  ----
s t r u t   c r e a t i v e

Dave Cunnington
Project Manager of Technology

Phone: 1-403-228-9200 ext. 108
Address: 101, 255 - 17th Avenue SW Calgary Alberta  T2S 2T8

Website: www.strutcreative.com <http://www.strutcreative.com/>  Twitter: @Strut_Creative
LinkedIn: ca.linkedin.com/in/davecunnington

The information transmitted in and with this message is intended only for the addressee and may contain confidential, proprietary and/or privileged material. If you received this in error, please contact the sender and delete or destroy this message and any copies.

**Comment by bobtiki** [comment]
Thanks, CiTroNaK! I have different responses for both:

    $ ruby -v
    ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    $ which bundle
    /Applications/Server.app/Contents/ServerRoot/usr/bin/bundle

    $ sudo su git
    $ ruby -v
    ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    $ which bundle
    /Users/git/.rbenv/shims/bundle

**Comment by CiTroNaK** [comment]
@davecunnington and @bobtiki: thanks.

The `sudo -u git -H -i` should works.

I have:

```
sudo -u git -H which bundle
/Users/server/.rvm/gems/ruby-2.2.2/bin/bundle
sudo -u git -H -i which bundle
/Users/git/.rbenv/shims/bundle
```

The `/Users/git/.rbenv/shims/bundle` is right and you should see that too. The `-i` parameter is important.

@bobtiki try to install it same way as @davecunnington done it.

**Comment by bobtiki** [comment]
@CiTroNaK so with this?

    sudo su git
    bundle install --deployment --without development test mysql aws

Thanks, will try.

**Comment by CiTroNaK** [comment]
@bobtiki yes.

**Comment by bobtiki** [comment]
I did:

    $ sudo su git
    $ bundle install --deployment --without development test mysql aws

Then I got this:

-----
    
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/git/.rbenv/versions/2.1.6/bin/bundle install --deployment --without development test mysql aws`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/git/gitlab/vendor/bundle/ruby/2.1.0
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:208:in `each'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler.rb:308:in `mkdir_p'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/installer.rb:278:in `create_bundle_path'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/installer.rb:54:in `run'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/installer.rb:18:in `install'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli/install.rb:107:in `run'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli.rb:162:in `install'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/git/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /Users/git/.rbenv/versions/2.1.6/bin/bundle:23:in `load'
      /Users/git/.rbenv/versions/2.1.6/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.5
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    GEM_HOME  /Users/git/gitlab/vendor/bundle/ruby/2.1.0
    GEM_PATH  
    Git       2.3.2 (Apple Git-55)

Bundler settings

    frozen
      Set for your local app (/Users/git/gitlab/.bundle/config): "1"
    path
      Set for your local app (/Users/git/gitlab/.bundle/config): "vendor/bundle"
    without
      Set for your local app (/Users/git/gitlab/.bundle/config): "development:test:mysql:aws"
    disable_shared_gems
      Set for your local app (/Users/git/gitlab/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fgit%2Fgitlab%2Fvendor%2Fbundle%2Fruby%2F2.1.0&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

-----

**Comment by CiTroNaK** [comment]
As admin user (previous user) run this
```
sudo chown -R git:git /Users/git/gitlab/vendor/bundle/ruby
```

And try it again.

**Comment by bobtiki** [comment]
It looks like this step may be solved. I see your note about `nokogiri` in the walkthrough, so I'll attempt that tomorrow (after some sleep), and also double-check that the Xcode command line tools are installed properly, as noted in the error. Thanks!

(including just in case:)

	$ sudo chown -R git:git /Users/git/gitlab/vendor/bundle/ruby
	$ sudo su git
	$ cd /Users/git/gitlab
	$ bundle install --deployment --without development test mysql aws
	Fetching gem metadata from https://rubygems.org/........
	Fetching version metadata from https://rubygems.org/...
	Fetching dependency metadata from https://rubygems.org/..
	Installing rake 10.4.2
	Installing CFPropertyList 2.3.1
	Installing RedCloth 4.2.9 with native extensions
	Installing ace-rails-ap 2.0.1
	Installing i18n 0.7.0
	Installing json 1.8.3 with native extensions
	Installing minitest 5.3.5
	Installing thread_safe 0.3.5
	Installing tzinfo 1.2.2
	Installing activesupport 4.1.11
	Installing builder 3.2.2
	Installing erubis 2.7.0
	Installing actionview 4.1.11
	Installing rack 1.5.4
	Installing rack-test 0.6.3
	Installing actionpack 4.1.11
	Installing mime-types 1.25.1
	Installing mail 2.6.3
	Installing actionmailer 4.1.11
	Installing activemodel 4.1.11
	Installing arel 5.0.1.20140414130214
	Installing activerecord 4.1.11
	Installing rails-observers 0.1.2
	Installing activeresource 4.0.0
	Installing acts-as-taggable-on 3.5.0
	Installing addressable 2.3.8
	Installing asana 0.0.6
	Installing asciidoctor 1.5.2
	Installing encryptor 1.3.0
	Installing attr_encrypted 1.3.4
	Installing attr_required 1.0.0
	Installing execjs 2.5.2
	Installing autoprefixer-rails 5.1.11
	Installing descendants_tracker 0.0.3
	Installing ice_nine 0.10.0
	Installing axiom-types 0.0.5
	Installing bcrypt 3.1.7 with native extensions
	Installing sass 3.2.19
	Installing bootstrap-sass 3.3.4.1
	Installing browser 0.8.0
	Installing cal-heatmap-rails 0.0.1
	Installing carrierwave 0.9.0
	Installing hitimes 1.2.2 with native extensions
	Installing timers 4.0.1
	Installing celluloid 0.16.0
	Installing charlock_holmes 0.7.2 with native extensions
	Installing coercible 1.0.0
	Installing coffee-script-source 1.9.1.1
	Installing coffee-script 2.4.1
	Installing thor 0.19.1
	Installing railties 4.1.11
	Installing coffee-rails 4.1.0
	Installing colored 1.2
	Installing connection_pool 2.1.0
	Installing creole 0.3.8
	Installing d3_rails 3.5.5
	Installing default_value_for 3.0.0
	Installing orm_adapter 0.5.0
	Installing warden 1.2.3
	Installing devise 3.2.4
	Installing devise-async 0.9.0
	Using bundler 1.10.5
	Installing hike 1.2.3
	Installing multi_json 1.11.1
	Installing tilt 1.4.1
	Installing sprockets 2.11.0
	Installing sprockets-rails 2.3.1
	Installing rails 4.1.11
	Installing rotp 1.6.1
	Installing devise-two-factor 1.0.1
	Installing diff-lcs 1.2.5
	Installing diffy 3.0.3
	Installing doorkeeper 2.1.3
	Installing dotenv 0.9.0
	Installing dropzonejs-rails 0.4.14
	Installing enumerize 0.7.0
	Installing equalizer 0.0.8
	Installing escape_utils 0.2.4 with native extensions
	Installing eventmachine 1.0.4 with native extensions
	Installing excon 0.45.3
	Installing expression_parser 0.9.0
	Installing multipart-post 1.2.0
	Installing faraday 0.8.9
	Installing faraday_middleware 0.9.0
	Installing fission 0.5.0
	Installing formatador 0.2.5
	Installing net-ssh 2.9.2
	Installing net-scp 1.2.1
	Installing fog-core 1.30.0
	Installing fog-json 1.0.2
	Installing inflecto 0.0.2
	Installing fog-brightbox 0.7.1
	Installing mini_portile 0.6.2
	Installing nokogiri 1.6.6.2 with native extensions

	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

		/Users/git/.rbenv/versions/2.1.6/bin/ruby extconf.rb
	checking if the C compiler accepts ... yes
	checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
	Building nokogiri using packaged libraries.
	-----
	The file "/usr/include/iconv.h" is missing in your build environment,
	which means you haven't installed Xcode Command Line Tools properly.

	To install Command Line Tools, try running `xcode-select --install` on
	terminal and follow the instructions.  If it fails, open Xcode.app,
	select from the menu "Xcode" - "Open Developer Tool" - "More Developer
	Tools" to open the developer site, download the installer for your OS
	version and run it.
	-----
	*** extconf.rb failed ***
	Could not create Makefile due to some reason, probably lack of necessary
	libraries and/or headers.  Check the mkmf.log file for more details.  You may
	need configuration options.

	Provided configuration options:
		--with-opt-dir
		--without-opt-dir
		--with-opt-include
		--without-opt-include=${opt-dir}/include
		--with-opt-lib
		--without-opt-lib=${opt-dir}/lib
		--with-make-prog
		--without-make-prog
		--srcdir=.
		--curdir
		--ruby=/Users/git/.rbenv/versions/2.1.6/bin/ruby
		--help
		--clean
		--use-system-libraries
		--enable-static
		--disable-static
		--with-zlib-dir
		--without-zlib-dir
		--with-zlib-include
		--without-zlib-include=${zlib-dir}/include
		--with-zlib-lib
		--without-zlib-lib=${zlib-dir}/lib
		--enable-cross-build
		--disable-cross-build

	extconf failed, exit code 1

	Gem files will remain installed in /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
	Results logged to /Users/git/gitlab/vendor/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/nokogiri-1.6.6.2/gem_make.out
	An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
	continue.
	Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

**Comment by DnR-iData** [comment]
I have the same issue.

The :
```
$ sudo -u git git add Gemfile
```
Says 1 Gem installed.

After for success I have to do :
```
$ sudo su git
$ cd /Users/git/gitlab
$ bundle install --deployment --without development test mysql aws
```

And the stdout :
![capture d ecran 2015-07-07 a 15 52 06](https://cloud.githubusercontent.com/assets/2852024/8547593/43bf7c46-24c0-11e5-844d-a9f92c13425e.png)


Hope can help you.

Thx

**Comment by bobtiki** [comment]
Just to follow up, after re-installing the Xcode command line tools, the bundle command completed successfully. Thanks for the help!

**Comment by robjdlc** [comment]
I'm experiencing the same issues as the other folks here but haven't found a resolution yet (Could not locate Gemfile), even though I've tried all of the above, including enter user git with su, made sure command line tools are installed properly, chowning the vender/bundle/ruby folder, and running it as the git user on that machine.

Any additional pointers to get around this?

Additionally, the installation guide reads:
**In case if you are using postgres as database:**

``sudo -u git -H -i gem install bundler``
``sudo -u git -H -i bundle install --deployment --without development test mysql aws``
**In case if you are using mysql as database:**

``sudo -u git -H -i gem install bundler``
``sudo -u git -H -i bundle install --deployment --without development test postgres aws``

Shouldn't it be the other way around?

**Comment by scottcc** [comment]
It should not be the other way around. the `--without` argument near the end there says "don't install any packages after my token". Thus, for "using mysql", it is skipping these four packages: `development test postgres aws`

**Comment by robjdlc** [comment]
Oh certainly, my mistake.

Unfortunately, that doesn't do anything to resolve my issue.

**Comment by scottcc** [comment]
Yeah, sadly I don't have anything else to offer on that issue. We experienced it as well; haven't had a chance to try fresh with the new suggestions yet.

**Comment by johnantoni** [comment]
Getting the same problem myself.

Doing 

    sudo -u git -H -i ls

Returns the git user's home directory and not where the gitlab repository and the Gemfile is located which makes sense why it can't find the Gemfile.

Will try the other suggestions.

**Comment by johnantoni** [comment]
Fetching gem metadata from https://rubygems.org/........
    Fetching version metadata from https://rubygems.org/...
    Fetching dependency metadata from https://rubygems.org/..
    Installing rake 10.4.2
    Installing CFPropertyList 2.3.1
    Installing RedCloth 4.2.9 with native extensions
    Installing ace-rails-ap 2.0.1
    Installing i18n 0.7.0
    Installing json 1.8.3 with native extensions
    Installing minitest 5.3.5
    Installing thread_safe 0.3.5
    Installing tzinfo 1.2.2
    Installing activesupport 4.1.11
    Installing builder 3.2.2
    Installing erubis 2.7.0
    Installing actionview 4.1.11
    Installing rack 1.5.4
    Installing rack-test 0.6.3
    Installing actionpack 4.1.11
    Installing mime-types 1.25.1
    Installing mail 2.6.3
    Installing actionmailer 4.1.11
    Installing activemodel 4.1.11
    Installing arel 5.0.1.20140414130214
    Installing activerecord 4.1.11
    Installing rails-observers 0.1.2
    Installing activeresource 4.0.0
    Installing acts-as-taggable-on 3.5.0
    Installing addressable 2.3.8
    Installing asana 0.0.6
    Installing asciidoctor 1.5.2
    Installing encryptor 1.3.0
    Installing attr_encrypted 1.3.4
    Installing attr_required 1.0.0
    Installing execjs 2.5.2
    Installing autoprefixer-rails 5.1.11
    Installing descendants_tracker 0.0.3
    Installing ice_nine 0.10.0
    Installing axiom-types 0.0.5
    Installing bcrypt 3.1.7 with native extensions
    Installing sass 3.2.19
    Installing bootstrap-sass 3.3.4.1
    Installing browser 0.8.0
    Installing cal-heatmap-rails 0.0.1
    Installing carrierwave 0.9.0
    Installing hitimes 1.2.2 with native extensions
    Installing timers 4.0.1
    Installing celluloid 0.16.0
    Installing charlock_holmes 0.7.2 with native extensions
    Installing coercible 1.0.0
    Installing coffee-script-source 1.9.1.1
    Installing coffee-script 2.4.1
    Installing thor 0.19.1
    Installing railties 4.1.11
    Installing coffee-rails 4.1.0
    Installing colored 1.2
    Installing connection_pool 2.1.0
    Installing creole 0.3.8
    Installing d3_rails 3.5.5
    Installing default_value_for 3.0.0
    Installing orm_adapter 0.5.0
    Installing warden 1.2.3
    Installing devise 3.2.4
    Installing devise-async 0.9.0
    Using bundler 1.10.6
    Installing hike 1.2.3
    Installing multi_json 1.11.1
    Installing tilt 1.4.1
    Installing sprockets 2.11.0
    Installing sprockets-rails 2.3.1
    Installing rails 4.1.11
    Installing rotp 1.6.1
    Installing devise-two-factor 1.0.1
    Installing diff-lcs 1.2.5
    Installing diffy 3.0.3
    Installing doorkeeper 2.1.3
    Installing dotenv 0.9.0
    Installing dropzonejs-rails 0.4.14
    Installing enumerize 0.7.0
    Installing equalizer 0.0.8
    Installing escape_utils 0.2.4 with native extensions
    Installing eventmachine 1.0.4 with native extensions
    Installing excon 0.45.3
    Installing expression_parser 0.9.0
    Installing multipart-post 1.2.0
    Installing faraday 0.8.9
    Installing faraday_middleware 0.9.0
    Installing fission 0.5.0
    Installing formatador 0.2.5
    Installing net-ssh 2.9.2
    Installing net-scp 1.2.1
    Installing fog-core 1.30.0
    Installing fog-json 1.0.2
    Installing inflecto 0.0.2
    Installing fog-brightbox 0.7.1
    Installing mini_portile 0.6.2
    Installing nokogiri 1.6.6.2 with native extensions
    Installing fog-xml 0.1.2
    Installing fog-profitbricks 0.0.3
    Installing fog-radosgw 0.0.4
    Installing fog-sakuracloud 1.0.1
    Installing fog-softlayer 0.4.6
    Installing fog-terremark 0.1.0
    Installing fog-vmfusion 0.1.0
    Installing fog-voxel 0.1.0
    Installing ipaddress 0.8.0
    Installing trollop 2.1.2
    Installing rbvmomi 1.8.2
    Installing opennebula 4.12.1
    Installing fog 1.25.0
    Installing font-awesome-rails 4.2.0.0
    Installing foreman 0.63.0
    Installing rugged 0.22.2 with native extensions
    Installing gemnasium-gitlab-service 0.2.6
    Installing gemojione 2.0.0
    Installing posix-spawn 0.3.9 with native extensions
    Installing github-markup 1.3.1
    Installing gitlab-grit 2.7.2
    Installing gitlab-flowdock-git-hook 0.4.2.2
    Installing gitlab-grack 2.0.2
    Installing gitlab-linguist 3.0.1
    Installing gitlab_emoji 0.1.0
    Installing gitlab_git 7.2.5
    Installing gitlab_meta 7.0
    Installing net-ldap 0.11
    Installing hashie 2.1.2
    Installing omniauth 1.2.2
    Installing pyu-ruby-sasl 0.0.3.3
    Installing rubyntlm 0.5.0
    Installing gitlab_omniauth-ldap 1.2.1
    Installing gollum-grit_adapter 0.1.3
    Installing rouge 1.7.7
    Installing sanitize 2.1.0
    Installing stringex 2.5.2
    Installing gollum-lib 4.0.2
    Installing gon 5.0.1
    Installing multi_xml 0.5.5
    Installing rack-accept 0.4.5
    Installing rack-mount 0.8.3
    Installing virtus 1.0.1
    Installing grape 0.6.1
    Installing grape-entity 0.4.2
    Installing haml 4.0.5
    Installing haml-rails 0.5.3
    Installing httparty 0.13.3
    Installing mimemagic 0.3.0
    Installing hipchat 1.5.0
    Installing html-pipeline 1.11.0
    Installing http_parser.rb 0.5.3 with native extensions
    Installing httpauth 0.2.1
    Installing httpclient 2.5.3.3
    Installing ice_cube 0.11.1
    Installing jquery-atwho-rails 1.0.1
    Installing jquery-rails 3.1.3
    Installing jquery-scrollto-rails 1.4.3
    Installing turbolinks 2.5.3
    Installing jquery-turbolinks 2.0.1
    Installing jquery-ui-rails 4.2.1
    Installing jwt 0.1.13
    Installing kaminari 0.15.1
    Installing kgio 2.9.2 with native extensions
    Installing systemu 2.6.5
    Installing macaddr 1.7.1
    Installing mousetrap-rails 1.4.6
    Installing newrelic_rpm 3.9.4.245
    Installing nprogress-rails 0.1.2.3
    Installing oauth 0.4.7
    Installing oauth2 0.8.1
    Installing sawyer 0.6.0
    Installing octokit 3.7.0
    Installing omniauth-oauth 1.0.1
    Installing omniauth-bitbucket 0.0.2
    Installing omniauth-oauth2 1.1.1
    Installing omniauth-github 1.1.1
    Installing omniauth-gitlab 1.0.0
    Installing omniauth-google-oauth2 0.2.5
    Installing omniauth-multipassword 0.4.1
    Installing timfel-krb5-auth 0.8.3 with native extensions
    Installing omniauth-kerberos 0.2.0
    Installing uuid 2.3.7
    Installing ruby-saml 0.8.2
    Installing omniauth-saml 1.3.1
    Installing omniauth-shibboleth 1.1.1
    Installing omniauth-twitter 1.0.1
    Installing rubypants 0.2.0
    Installing org-ruby 0.9.12
    Installing pg 0.15.1 with native extensions
    Installing rack-attack 4.3.0
    Installing rack-cors 0.2.9
    Installing rack-oauth2 1.0.8
    Installing rack-protection 1.5.1
    Installing raindrops 0.13.0 with native extensions
    Installing raphael-rails 2.1.2
    Installing rdoc 3.12.2
    Installing redcarpet 3.2.3 with native extensions
    Installing redis 3.1.0
    Installing redis-store 1.1.4
    Installing redis-rack 1.5.0
    Installing redis-actionpack 4.0.0
    Installing redis-activesupport 4.0.0
    Installing redis-namespace 1.5.1
    Installing redis-rails 4.0.0
    Installing request_store 1.0.5
    Installing rinku 1.7.3 with native extensions
    Installing rqrcode 0.4.2
    Installing rqrcode-rails3 0.1.7
    Installing rugments 1.0.0.beta7
    Installing sass-rails 4.0.3
    Installing seed-fu 2.3.5
    Installing select2-rails 3.5.2
    Installing settingslogic 2.0.9
    Installing sidekiq 3.3.0
    Installing sidetiq 0.6.3
    Installing simple_oauth 0.1.9
    Installing sinatra 1.4.4
    Installing six 0.2.0
    Installing slack-notifier 1.0.0
    Installing temple 0.6.7
    Installing slim 2.0.2
    Installing stamp 0.5.0
    Installing state_machine 1.2.0
    Installing task_list 1.0.2
    Installing twitter-stream 0.1.16
    Installing tinder 1.9.3
    Installing uglifier 2.3.2
    Installing underscore-rails 1.5.2
    Installing unf_ext 0.0.6 with native extensions
    Installing unf 0.1.4
    Installing unicorn 4.6.3 with native extensions
    Installing unicorn-worker-killer 0.4.2
    Installing version_sorter 2.0.0 with native extensions
    Installing wikicloth 0.8.1
    Bundle complete! 136 Gemfile dependencies, 229 gems now installed.
    Gems in the groups development, test, mysql and aws were not installed.
    Bundled gems are installed into ./vendor/bundle.
    Post-install message from acts-as-taggable-on:
    When upgrading

    Re-run the migrations generator

        rake acts_as_taggable_on_engine:install:migrations

    This will create any new migrations and skip existing ones
    Version 3.5.0 has a migration for mysql adapter
    Post-install message from haml:

    HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
    your application:

    * Support for Ruby 1.8.6 dropped
    * Support for Rails 2 dropped
    * Sass filter now always outputs <style> tags
    * Data attributes are now hyphenated, not underscored
    * html2haml utility moved to the html2haml gem
    * Textile and Maruku filters moved to the haml-contrib gem

    For more info see:

    http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

    Post-install message from httparty:
    When you HTTParty, you must party hard!
    Post-install message from html-pipeline:
    -------------------------------------------------
    Thank you for installing html-pipeline!
    You must bundle Filter gem dependencies.
    See html-pipeline README.md for more details.
    https://github.com/jch/html-pipeline#dependencies
    -------------------------------------------------
    Post-install message from mousetrap-rails:

    Remember to run generator to generate sample file and include mousetrap-rails with Rails Asset Pipeline

        $ rails generate mousetrap:install 

    Post-install message from rdoc:
    Depending on your version of ruby, you may need to install ruby rdoc/ri data:

    <= 1.8.6 : unsupported
     = 1.8.7 : gem install rdoc-data; rdoc-data --install
     = 1.9.1 : gem install rdoc-data; rdoc-data --install
    >= 1.9.2 : nothing to do! Yay!

**Comment by warmpark** [comment]
It's OK!!! 

sudo -u git -H -i BUNDLE_GEMFILE="~/gitlab/Gemfile" bundle install --deployment --without development test postgres aws

**Comment by CiTroNaK** [comment]
Gitlab recommended to not use version managers for ruby. This is the perfect example of the problems with them, but we are forced to use them...

I updated the guide.

**Comment by XSecr3t** [comment]
[ Error While Install Nokogiri 1.8.0 ]

Excuse Me
Hello sir greetings

I have some problem can anybody help me?

I want install Nokogiri 1.8.0 but cant cause have error like this

> To see why this extension failed to compile, please check the mkmf.log which can be found here:
>/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/mkmf.log
> extconf failed, exit code 1
> Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/gem_make.out

I have already run any command that i see like

> gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]
Or
> bundle config build.nokogiri --use-system-libraries
    bundle install

But the result still same, exit  ode 1

So what should i do?
I already uninstalled and installed again my termux 10times since 2 day ago
And Rebuild Package but the result still same,error code 1
It sucks for me can anyone help me sir?

It would be pleasure if somebody help me for guide me how to fix this problems.
First time i use termux looks good and everything is fine,but after 3 or 4 month everything has change,i already update every second every files and package but the result still same.

Somebody please help me🙁🙁

Because this problem i cannot run my metasploit again.

> here more error : http://i67.tinypic.com/343maoh.png
http://i67.tinypic.com/2ahz9f9.png
http://i66.tinypic.com/23w08yr.png
http://i67.tinypic.com/4uyk1y.png
http://i65.tinypic.com/2w7ph12.png
http://i68.tinypic.com/2vjph6r.png
http://i67.tinypic.com/20shis5.png

I think someone can help me for solve this,i dont know what i want to do again,,,
I'll do everything but still same

i try to used following command

> LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries.

But the result said i installed nokogiri 1.8.5 not 1.8.0 versions,my metasploit needs nokogiri 1.8.0 not 1.8.5

> result :
LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Building native extensions with: '--use-system-libraries'
This could take a while...
Successfully installed nokogiri-1.8.5
Parsing documentation for nokogiri-1.8.5
Done installing documentation for nokogiri after 10 seconds
1 gem installed
root@Mr.XSecr3t:#

When i run msfconsole result said

> root@Mr.XSecr3t:#msfconsole
Could not find nokogiri-1.8.0 in any of the sources
Run bundle install to install missing gems.
root@Mr.XSecr3t:#

And when i run bundle install the result said

> root@Mr.XSecr3t:#bundle install
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Could not locate Gemfile
root@Mr.XSecr3t:#

so can anybody help me fix this problems? i dont know what i want to do,i cant run my metasploit again. 🙁🙁

thanks for helping me and reply my issued!
