### ISSUE TITLE
Trying to start gitlab instance throws me into git shell

### ISSUE THREAD

**Issue by ritave** [WebEntity/Installation-guide-for-GitLab-on-OS-X#56]
When I run ```sudo sh /etc/init.d/gitlab start``` the instance doesn't start. Instead I am thrown into git user account shell, like so:
```
MacMini:gitlab ritave$ sudo sh /etc/init.d/gitlab start
MacMini:~ git$
```

**Comment by ritave** [comment]
I got further by editing line 55 of ```/etc/init.d/gitlib``` to point to ```/Users/$app_user/gitlab``` instead of ```/home/...``` and then running /etc/init.d/gitlab from git user:
```MacMini:~ git$ /etc/init.d/gitlab start```
I get stoppped at Unicorn though it said that 127.0.0.1:8080 was already in use. I tried accessing that with browser and well enough I got a greeting from nginx which I killed and gitlab successfully started.

I killed ngins and edited /etc/nginx/nginx.conf and disabled sample 8080 server (why was it there I don't know, imho a bad place for examples).

Afterwards after starting gitlab from git user I can succesfully access the server.

**Comment by berkedel** [comment]
I got the same problem. I just changed the default port to another one such as 8888.

**Comment by CiTroNaK** [comment]
You should read section "Install Init Script" again...

< If you installed GitLab in another directory or as a user other than the default you should change these settings in /etc/default/gitlab. Do not edit /etc/init.d/gitlab as it will be changed on upgrade.

**Comment by ritave** [comment]
@CiTroNaK Oh true, sorry. Then I think the section is little unclear - I installed in default directory your guide stated and thus assumed that I shouldn't then install ```/etc/default/gitlab```. Since the file is required may I suggest changing the description stating that everyone doing Mac OS X install should copy this file?

Something like this:
>Since you are installing with a non-default folder download from this repo and copy the defaults file.

I'll do a pull request
