### ISSUE TITLE
Error adding listener, 'Invalid argument' socket issue starting Unicorn & gitlab http server

### ISSUE THREAD

**Issue by raldred** [WebEntity/Installation-guide-for-GitLab-on-OS-X#59]
I followed the OSX installation instructions on my OSX server 10.8.
Thanks for such thorough instructions, unfortunately I've fallen at the final hurdle, getting it all running.

Unicorn & the gitlab http server won't start.
Giveing the following error (full error logs below):

    F, [2015-11-09T11:31:55.464083 #75537] FATAL -- : error adding listener addr=/Users/git/gitlab/tmp/sockets/gitlab.socket
    /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/socket_helper.rb:158:in `initialize': Invalid argument - connect(2) for /Users/git/gitlab/tmp/sockets/gitlab.socket (Errno::EINVAL)

Errno::EINVAL according to the [ruby docs for socket](http://ruby-doc.org/stdlib-2.1.7/libdoc/socket/rdoc/Socket.html#method-i-connect)

> Errno::EINVAL - the address length used for the sockaddr is not a valid length for the address family or there is an invalid family in sockaddr

I've checked permissions on the sockets dir, infact there are two sockets in there so they're being created.
I tried skipping the init script incase there was something funky going on, I ran unicorn manually with `bundle exec unicorn_rails -D -c config/unicorn.rb -E production`
It gives the same issue.

Here's the port/socket config from `config/unicorn.rb`

    listen "/Users/git/gitlab/tmp/sockets/gitlab.socket", :backlog => 1024
    listen "127.0.0.1:8085", :tcp_nopush => true

=> unicorn.stderr.log

	I, [2015-11-09T11:27:03.675686 #75337]  INFO -- : Refreshing Gem list
	F, [2015-11-09T11:27:13.813564 #75337] FATAL -- : error adding listener addr=/Users/git/gitlab/tmp/sockets/gitlab.socket
	/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/socket_helper.rb:158:in `initialize': Invalid argument - connect(2) for /Users/git/gitlab/tmp/sockets/gitlab.socket (Errno::EINVAL)
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/socket_helper.rb:158:in `new'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/socket_helper.rb:158:in `bind_listen'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:242:in `listen'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:809:in `block in bind_new_listeners!'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:809:in `each'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:809:in `bind_new_listeners!'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:138:in `start'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
		from /Users/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'

=> gitlab-git-http-server.log

	2015/11/09 11:27:14 Starting gitlab-git-http-server 0.3.0-20151106.175414
	2015/11/09 11:27:14 listen unix /Users/git/gitlab/tmp/sockets/gitlab-git-http-server.socket: bind: invalid argument

**Comment by raldred** [comment]
So... 
I managed to get this working by changing the sockets so they're stored in root /tmp so the path is shorter, maybe there's a limit on OSX to the length of the socket name? Weird.

**Comment by CiTroNaK** [comment]
I don't have any problem with it. There could be problem with some differences between OS X versions or you didn't follow the guide correctly.
