### ISSUE TITLE
Redis is not starting

### ISSUE THREAD

**Issue by jay3126** [WebEntity/Installation-guide-for-GitLab-on-OS-X#63]
When i run the following command - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
 redis does not start. I came to know about this as there is no processes which is running.

Also, when I try to check the application using bundle exec rake gitlab:env:info RAILS_ENV=production

it throws me the following error - /var/run/redis/redis.sock: No such file or directory

Can you let me know what I am doing wrong. I am running Mac OS X El Capitan. I need to install Gitlab urgently.

**Comment by CiTroNaK** [comment]
```
To reload redis after an upgrade:
  launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
Or, if you don't want/need launchctl, you can just run:
  redis-server /usr/local/etc/redis.conf
```

Try to run it using `redis-server /usr/local/etc/redis.conf`.

**Comment by CiTroNaK** [comment]
Also try to check, if you create correct simplink 

```
ls -la ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```
You should see:

```
lrwxr-xr-x  1 Petr  staff  46  2 čvc  2015 /Users/Petr/Library/LaunchAgents/homebrew.mxcl.redis.plist -> /usr/local/opt/redis/homebrew.mxcl.redis.plist
```

**Comment by jay3126** [comment]
Simplelink output is as follows:

lrwxr-xr-x  1 jay  staff  46 Feb 10 15:30 /Users/jay/Library/LaunchAgents/homebrew.mxcl.redis.plist -> /usr/local/opt/redis/homebrew.mxcl.redis.plist

When I run: redis-server /usr/local/etc/redis.conf

following is the output:

20963:M 11 Feb 21:03:41.029 * Increased maximum number of open files to 10032 (it was originally set to 256).
20963:M 11 Feb 21:03:41.030 # Opening Unix socket: bind: No such file or directory

Now when I check for redis running process, this is the result:
ps aux|grep redis
jay             20984   0.0  0.0  2434840    756 s001  S+    9:04PM   0:00.00 grep redis

When I am trying launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
it is also not starting the redis server.

Plzz suggest what to do next.

**Comment by CiTroNaK** [comment]
Did you follow up guide in section about Redis carefully? Did you change `/usr/local/etc/redis.conf`?

**Comment by jay3126** [comment]
I guess I did. I followed all the steps. In following url you can see the contents of my redis.conf file.

http://pastie.org/private/ww2gnangueycvadmkmsxwa

Let me know if there is anything which I did not change.

**Comment by CiTroNaK** [comment]
Seriously? 

Edit file (`nano /usr/local/etc/redis.conf`) and **uncomment**:

```
unixsocket /tmp/redis.sock
unixsocketperm 777
```

**Comment by jay3126** [comment]
No luck. After doing that also, following is the result:

redis-server /usr/local/etc/redis.conf
21905:M 12 Feb 00:41:42.394 * Increased maximum number of open files to 10032 (it was originally set to 256).
21905:M 12 Feb 00:41:42.395 # Opening Unix socket: bind: No such file or directory

**Comment by CiTroNaK** [comment]
No idea why. It works for me and everyone else here.

```
ls -la /tmp/redis.sock
srwxrwxrwx  1 iportal  wheel     0B  1 úno 11:31 /tmp/redis.sock
```

You should do every step again in Redis section.

**Comment by jay3126** [comment]
ls -la /tmp/redis.sock
ls: /tmp/redis.sock: No such file or directory

This is what it says...

**Comment by jay3126** [comment]
After un-installing and reinstalling, the redis server has started and I can see the process also but now when I am trying to run **bundle exec rake gitlab:env:info RAILS_ENV=production**
it is throwing this error:

D, [2016-02-12T00:52:40.042375 #22384] DEBUG -- : ** [Raven] Event not sent due to excluded environment: production
rake aborted!
**Errno::ENOENT: No such file or directory - connect(2) for /var/run/redis/redis.sock**
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:180:in `connect_nonblock'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:180:in `connect'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:209:in `connect'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:822:in `block in get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.2/lib/redis.rb:821:in `get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/interface.rb:5:in `get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/marshalling.rb:17:in `get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:21:in `block in get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:74:in `namespace'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:21:in `get'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:230:in `block in read_entry'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:212:in `call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:212:in `with'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:230:in `read_entry'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache.rb:558:in `block in find_cached_entry'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache.rb:547:in `block in instrument'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache.rb:547:in `instrument'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache.rb:556:in `find_cached_entry'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache.rb:293:in `fetch'
/Users/git/gitlab/app/models/application_setting.rb:120:in `current'
/Users/git/gitlab/lib/gitlab/current_settings.rb:8:in `current_application_settings'
/Users/git/gitlab/lib/gitlab/metrics.rb:11:in `settings'
/Users/git/gitlab/lib/gitlab/metrics.rb:22:in `enabled?'
/Users/git/gitlab/lib/gitlab/metrics.rb:75:in `<module:Metrics>'
/Users/git/gitlab/lib/gitlab/metrics.rb:2:in `<module:Gitlab>'
/Users/git/gitlab/lib/gitlab/metrics.rb:1:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:184:in `const_missing'
/Users/git/gitlab/config/initializers/metrics.rb:1:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:651:in `load_config_initializer'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
/Users/git/gitlab/config/environment.rb:5:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => gitlab:env:info => environment
(See full trace by running task with --trace)

**Comment by CiTroNaK** [comment]
Ok, you should do **EVERY** step again.

You miss this one:

Configure Redis connection settings
```
sudo -u git -H cp config/resque.yml.example config/resque.yml
```

Change the Redis socket path to `/tmp/redis.sock`:
```
sudo -u git -H nano config/resque.yml
```

**Comment by jay3126** [comment]
When I am running following command: **bundle exec rake gitlab:check RAILS_ENV=production**

below is the output I am getting:

Checking GitLab Shell ...

GitLab Shell version >= 2.6.10 ? ... OK (2.6.10)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
hooks directories in repos are links: ... can't check, you have no projects
Running /Users/git/gitlab-shell/bin/check
**Check GitLab API access: FAILED: Failed to connect to internal API
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /Users/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.**

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking Reply by email ...

Reply by email is disabled in config/gitlab.yml

Checking Reply by email ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Uploads directory setup correctly? ... skipped (no tmp uploads folder yet)
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... can't check, you have no projects
Redis version >= 2.8.0? ... yes
Ruby version >= 2.1.0 ? ... yes (2.1.7)
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (2.6.4)
Active users: 1

Checking GitLab ... Finished

Output of **sudo sh /etc/init.d/gitlab start** command is as follows:

/etc/init.d/gitlab: line 41: cd: /home/git/gitlab/../gitlab-workhorse: No such file or directory
/etc/init.d/gitlab: line 41: cd: /home/git/gitlab/../gitlab-workhorse: No such file or directory
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-darwin15.0]
Removing stale Unicorn web server pid. This is most likely caused by the web server crashing the last time it ran.
Removing stale Sidekiq job dispatcher pid. This is most likely caused by Sidekiq crashing the last time it ran.
Starting GitLab Unicorn
Starting GitLab Sidekiq
The gitlab-workhorse is already running with pid 27415, not restarting
-n .
-n .

The GitLab Unicorn web server with pid 29015 is running.
The GitLab Sidekiq job dispatcher with pid 29084 is running.
The gitlab-workhorse with pid 27393 is running.
GitLab and all its components are up and running.

My gitlab is located in following folder: **/Users/git/gitlab** and its component's are located in following folder: **/Users/git**

The check is failing. Can you help me in this.

**Comment by CiTroNaK** [comment]
run in terminal:

```
sudo sed -i "" "s/\/home\//\/Users\//g" /etc/init.d/gitlab
```

**Comment by jay3126** [comment]
After running this command, following errors are coming when trying to check the application status:

Running /Users/git/gitlab-shell/bin/check
**Check GitLab API access: FAILED: Failed to connect to internal API
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /Users/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.
**
Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking Reply by email ...

Reply by email is disabled in config/gitlab.yml

Checking Reply by email ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Uploads directory setup correctly? ... skipped (no tmp uploads folder yet)
Init script exists? ... yes
**Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.**
projects have namespace: ... can't check, you have no projects
Redis version >= 2.8.0? ... yes
Ruby version >= 2.1.0 ? ... yes (2.1.7)
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (2.6.4)
Active users: 1

Checking GitLab ... Finished

**Comment by CiTroNaK** [comment]
BTW I am not here for a free support with your installation. Every error you had here was your fault because you didn't read everything (even errors) carefully.

I don't have more free time to spend it with you. If you need more help, I can install it for you for a fee.

**Comment by jay3126** [comment]
A BIG THANK YOU for sparing your FREE time for me. But NO THANKS. I am not buzzing you anymore.

**Comment by CiTroNaK** [comment]
Happy to help.

**Comment by jay3126** [comment]
But I am no more HAPPY to take ur help. I can take this forward on my own. I dont want you to spend any more FREE time on me.
