### ISSUE TITLE
Error pushing to GitLab

### ISSUE THREAD

**Issue by corydorning** [WebEntity/Installation-guide-for-GitLab-on-OS-X#64]
After setting a project up in GitLab I'm unable to push. When i try, I get the error:
```
fatal: unable to access 'http://site.com/corydorning/gxl-ng.git/': The requested URL returned error: 503
```

I'm assuming this is the same issue that returns a 500 page when i try to upload a new avatar under my profile as well. Is this a permissions issue? or something else?

**Comment by CiTroNaK** [comment]
You should look to logs.

**Comment by CiTroNaK** [comment]
What is your output from Gitlab Check?

```
bundle exec rake gitlab:check RAILS_ENV=production
```
