### ISSUE TITLE
can not connect via ssh

### ISSUE THREAD

**Issue by cyl19910101** [WebEntity/Installation-guide-for-GitLab-on-OS-X#66]
Thank you very much for writing this for us!
I think i almost there except the ssh connection. After doing step 1-7, I can browse the gitlab website via http. And I have a nginx running on the system already, So I just simply poxy_pass the request to port 8080 : 
`server {
listen 80;
server_name git.domain;
location / {
proxy_pass http://127.0.0.1:8080;
}
}`
I didn't configure ssl yet. The http requests seem be handled well by the nginx and gitlab. However, When I try to test it by create ( success )and clone a repository from it, I got some errors and can not clone the repository.

I have tried to use ssh to connect the git account, and failed(Already add public key to git account's authorized_keys  --  connection closed by 192.168......)

I'm not very familiar with os x account settings, Is there something additional steps i should have done?(Since your tutorial do not give a password to git, I didn't set a password to it either.)

These are the error info I got:

(test in localhost)

`git clone git@127.0.0.1:***/ex.git`

**The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:..................**
**Are you sure you want to continue connecting (yes/no)?**` yes`
**Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
Connection closed by 127.0.0.1
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.**

(test in remote)

`git clone git@domain:***/ex.git `                                                                                                                                                        
**Cloning into 'ex'...
Connection closed by *****
**fatal: Could not read from remote repository.**

**Please make sure you have the correct access rights**

Do you have some ideas about this? Thank you very much in advance!

**Comment by cyl19910101** [comment]
Oh, finally get it done, give the git account ssh connect permission make it works.
Thanks a lot!

**Comment by CiTroNaK** [comment]
:-) I'll add it into the guide. Thanks.
